Run the cell below:

In [1]:
import pandas as pd

If you have not done so already, download the "compa.zip", "crspm.zip" and "ff.zip" files from the "Lectures and Data / data" tab in D2L into a "data" folder on your computer (located outside the folder containing this file, as explained in ``lecture00``).

Load the CRSP monthly market data ("crspm.zip") into a new dataframe called ``crsp``. Print all the data types in ``crsp``.

In [2]:
crsp = pd.read_pickle('../data/crspm.zip')
crsp.dtypes

permno    float64
permco    float64
date       object
prc       float64
ret       float64
shrout    float64
shrcd     float64
exchcd    float64
siccd     float64
ticker     object
dtype: object

Convert the ``date`` column to ``datetime`` type. Print all the data types again.

In [4]:
crsp['date'] = pd.to_datetime(crsp['date'])
crsp.dtypes

permno           float64
permco           float64
date      datetime64[ns]
prc              float64
ret              float64
shrout           float64
shrcd            float64
exchcd           float64
siccd            float64
ticker            object
dtype: object

Create a new column called ``mdate`` which contains a version of ``date`` converted to ``period`` type, with monthly frequency.

In [5]:
crsp['mdate'] = crsp['date'].dt.to_period('M')
crsp

,permno,permco,date,prc,ret,shrout,shrcd,exchcd,siccd,ticker,mdate
0,10000.0,7952.0,1986-01-31,-4.375000,NaN,3680.0,10.0,3.0,3990.0,OMFGA,1986-01
1,10000.0,7952.0,1986-02-28,-3.250000,-0.257143,3680.0,10.0,3.0,3990.0,OMFGA,1986-02
2,10000.0,7952.0,1986-03-31,-4.437500,0.365385,3680.0,10.0,3.0,3990.0,OMFGA,1986-03
3,10000.0,7952.0,1986-04-30,-4.000000,-0.098592,3793.0,10.0,3.0,3990.0,OMFGA,1986-04
4,10000.0,7952.0,1986-05-30,-3.109375,-0.222656,3793.0,10.0,3.0,3990.0,OMFGA,1986-05
...,...,...,...,...,...,...,...,...,...,...,...
2553282,10091.0,8034.0,1987-12-31,7.250000,0.348837,3931.0,11.0,3.0,3660.0,ITXI,1987-12
2553283,10091.0,8034.0,1988-01-29,7.500000,0.034483,3941.0,11.0,3.0,3660.0,ITXI,1988-01
2553284,10091.0,8034.0,1988-02-29,7.375000,-0.016667,3941.0,11.0,3.0,3660.0,ITXI,1988-02
2553285,10091.0,8034.0,1988-03-31,9.625000,0.305085,3941.0,11.0,3.0,3660.0,ITXI,1988-03
2553286,10091.0,8034.0,1988-04-29,10.375000,0.077922,3941.0,11.0,3.0,3660.0,ITXI,1988-04

Create a new column called ``date_6M_ago`` which equals the date 6 months prior to the date recorded in ``mdate``.

In [6]:
crsp['date_6M_ago'] = crsp['mdate'] - 6
crsp

,permno,permco,date,prc,ret,shrout,shrcd,exchcd,siccd,ticker,mdate,date_6M_ago
0,10000.0,7952.0,1986-01-31,-4.375000,NaN,3680.0,10.0,3.0,3990.0,OMFGA,1986-01,1985-07
1,10000.0,7952.0,1986-02-28,-3.250000,-0.257143,3680.0,10.0,3.0,3990.0,OMFGA,1986-02,1985-08
2,10000.0,7952.0,1986-03-31,-4.437500,0.365385,3680.0,10.0,3.0,3990.0,OMFGA,1986-03,1985-09
3,10000.0,7952.0,1986-04-30,-4.000000,-0.098592,3793.0,10.0,3.0,3990.0,OMFGA,1986-04,1985-10
4,10000.0,7952.0,1986-05-30,-3.109375,-0.222656,3793.0,10.0,3.0,3990.0,OMFGA,1986-05,1985-11
...,...,...,...,...,...,...,...,...,...,...,...,...
2553282,10091.0,8034.0,1987-12-31,7.250000,0.348837,3931.0,11.0,3.0,3660.0,ITXI,1987-12,1987-06
2553283,10091.0,8034.0,1988-01-29,7.500000,0.034483,3941.0,11.0,3.0,3660.0,ITXI,1988-01,1987-07
2553284,10091.0,8034.0,1988-02-29,7.375000,-0.016667,3941.0,11.0,3.0,3660.0,ITXI,1988-02,1987-08
2553285,10091.0,8034.0,1988-03-31,9.625000,0.305085,3941.0,11.0,3.0,3660.0,ITXI,1988-03,1987-09
2553286,10091.0,8034.0,1988-04-29,10.375000,0.077922,3941.0,11.0,3.0,3660.0,ITXI,1988-04,1987-10

Replace ``crsp`` with a version of itself sorted by the values of ``permno`` and ``date``.

In [7]:
crsp = crsp.sort_values(['permno','date'])
crsp

,permno,permco,date,prc,ret,shrout,shrcd,exchcd,siccd,ticker,mdate,date_6M_ago
0,10000.0,7952.0,1986-01-31,-4.375000,NaN,3680.0,10.0,3.0,3990.0,OMFGA,1986-01,1985-07
1,10000.0,7952.0,1986-02-28,-3.250000,-0.257143,3680.0,10.0,3.0,3990.0,OMFGA,1986-02,1985-08
2,10000.0,7952.0,1986-03-31,-4.437500,0.365385,3680.0,10.0,3.0,3990.0,OMFGA,1986-03,1985-09
3,10000.0,7952.0,1986-04-30,-4.000000,-0.098592,3793.0,10.0,3.0,3990.0,OMFGA,1986-04,1985-10
4,10000.0,7952.0,1986-05-30,-3.109375,-0.222656,3793.0,10.0,3.0,3990.0,OMFGA,1986-05,1985-11
...,...,...,...,...,...,...,...,...,...,...,...,...
2553248,93436.0,53453.0,2020-08-31,498.320007,0.741452,931809.0,11.0,3.0,9999.0,TSLA,2020-08,2020-02
2553249,93436.0,53453.0,2020-09-30,429.010010,-0.139087,948000.0,11.0,3.0,9999.0,TSLA,2020-09,2020-03
2553250,93436.0,53453.0,2020-10-30,388.040009,-0.095499,947901.0,11.0,3.0,9999.0,TSLA,2020-10,2020-04
2553251,93436.0,53453.0,2020-11-30,567.599976,0.462736,947901.0,11.0,3.0,9999.0,TSLA,2020-11,2020-05
2553252,93436.0,53453.0,2020-12-31,705.669983,0.243252,947901.0,11.0,3.0,9999.0,TSLA,2020-12,2020-06

Create a new column called ``lag6_ret`` which equals the firm's return from 6 periods (rows) prior. Use the ``.shift()`` method, with ``permno`` as the firm identifier. Then print the first 8 rows of ``crsp``.

In [9]:
crsp['lag6_ret'] = crsp.groupby('permno')['ret'].shift(6)
crsp.head(8)

,permno,permco,date,prc,ret,shrout,shrcd,exchcd,siccd,ticker,mdate,date_6M_ago,lag6_ret
0,10000.0,7952.0,1986-01-31,-4.375000,NaN,3680.0,10.0,3.0,3990.0,OMFGA,1986-01,1985-07,NaN
1,10000.0,7952.0,1986-02-28,-3.250000,-0.257143,3680.0,10.0,3.0,3990.0,OMFGA,1986-02,1985-08,NaN
2,10000.0,7952.0,1986-03-31,-4.437500,0.365385,3680.0,10.0,3.0,3990.0,OMFGA,1986-03,1985-09,NaN
3,10000.0,7952.0,1986-04-30,-4.000000,-0.098592,3793.0,10.0,3.0,3990.0,OMFGA,1986-04,1985-10,NaN
4,10000.0,7952.0,1986-05-30,-3.109375,-0.222656,3793.0,10.0,3.0,3990.0,OMFGA,1986-05,1985-11,NaN
5,10000.0,7952.0,1986-06-30,-3.093750,-0.005025,3793.0,10.0,3.0,3990.0,OMFGA,1986-06,1985-12,NaN
6,10000.0,7952.0,1986-07-31,-2.843750,-0.080808,3793.0,10.0,3.0,3990.0,OMFGA,1986-07,1986-01,NaN
7,10000.0,7952.0,1986-08-29,-1.093750,-0.615385,3793.0,10.0,3.0,3990.0,OMFGA,1986-08,1986-02,-0.257143